# Generated by Django 2.0.5 on 2018-05-14 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_maker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
    ]
