# Generated by Django 2.0.5 on 2019-06-26 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_maker', '0004_auto_20190626_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='Url',
        ),
    ]
