# Generated by Django 2.0.5 on 2019-06-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0005_auto_20190626_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
